AZURE_LOCATION: 'southeastasia'
RESOURCE_NAME_PREFIX: 'hieuapimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/hieumoscow'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'
